/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pathing_CONSTANTS_H
#define pathing_CONSTANTS_H

#include "pathing_types.h"

namespace pathing {

class pathingConstants {
 public:
  pathingConstants();

};

extern const pathingConstants g_pathing_constants;

} // namespace

#endif
